### ISSUE TITLE
'setup_nginx' and 'install_services' not found

### ISSUE THREAD

**Issue by fabge** [sebasgo/pi-dawn#1]
When trying to install pi-dawn I arrive at the following point:

`FLASK_APP=pi_dawn ./pi-dawn/bin/flask setup_nginx`

When I try to execute this command I get following error:

```
root@raspberrypi:~# FLASK_APP=pi_dawn ./pi-dawn/bin/flask setup_nginx
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "setup_nginx".
root@raspberrypi:~# FLASK_APP=pi_dawn ./pi-dawn/bin/flask install_services
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "install_services".
```

I am using Raspbian Buster, anything I can do to fix it?

**Comment by fabge** [comment]
In the comment from your post you said that `setup-nginx` and `install-services` is the correct syntax. But how can this be? In your p-dawn `__init__.py` you are defining your functions with an underscore `_`?

**Comment by sebasgo** [comment]
Flask (or, actually click) [replaces the underscores with dashes](https://click.palletsprojects.com/en/7.x/api/#click.command). It was really just a typo in the README, which is fixed now.
